/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// LED7SEG_1a address and mask defines
#pragma	ioport	LED7SEG_1a_Data_ADDR:	0x0
BYTE			LED7SEG_1a_Data_ADDR;
#pragma	ioport	LED7SEG_1a_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1a_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1a_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1a_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1a_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1a_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1a_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1a_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1a_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1a_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1a_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1a_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1a_IntEn_ADDR:	0x1
BYTE			LED7SEG_1a_IntEn_ADDR;
#define LED7SEG_1a_MASK 0x1
// LED7SEG_1b address and mask defines
#pragma	ioport	LED7SEG_1b_Data_ADDR:	0x0
BYTE			LED7SEG_1b_Data_ADDR;
#pragma	ioport	LED7SEG_1b_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1b_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1b_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1b_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1b_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1b_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1b_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1b_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1b_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1b_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1b_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1b_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1b_IntEn_ADDR:	0x1
BYTE			LED7SEG_1b_IntEn_ADDR;
#define LED7SEG_1b_MASK 0x2
// LED7SEG_1c address and mask defines
#pragma	ioport	LED7SEG_1c_Data_ADDR:	0x0
BYTE			LED7SEG_1c_Data_ADDR;
#pragma	ioport	LED7SEG_1c_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1c_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1c_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1c_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1c_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1c_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1c_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1c_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1c_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1c_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1c_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1c_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1c_IntEn_ADDR:	0x1
BYTE			LED7SEG_1c_IntEn_ADDR;
#define LED7SEG_1c_MASK 0x4
// LED7SEG_1d address and mask defines
#pragma	ioport	LED7SEG_1d_Data_ADDR:	0x0
BYTE			LED7SEG_1d_Data_ADDR;
#pragma	ioport	LED7SEG_1d_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1d_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1d_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1d_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1d_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1d_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1d_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1d_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1d_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1d_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1d_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1d_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1d_IntEn_ADDR:	0x1
BYTE			LED7SEG_1d_IntEn_ADDR;
#define LED7SEG_1d_MASK 0x8
// LED7SEG_1e address and mask defines
#pragma	ioport	LED7SEG_1e_Data_ADDR:	0x0
BYTE			LED7SEG_1e_Data_ADDR;
#pragma	ioport	LED7SEG_1e_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1e_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1e_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1e_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1e_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1e_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1e_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1e_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1e_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1e_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1e_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1e_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1e_IntEn_ADDR:	0x1
BYTE			LED7SEG_1e_IntEn_ADDR;
#define LED7SEG_1e_MASK 0x10
// LED7SEG_1f address and mask defines
#pragma	ioport	LED7SEG_1f_Data_ADDR:	0x0
BYTE			LED7SEG_1f_Data_ADDR;
#pragma	ioport	LED7SEG_1f_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1f_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1f_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1f_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1f_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1f_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1f_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1f_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1f_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1f_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1f_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1f_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1f_IntEn_ADDR:	0x1
BYTE			LED7SEG_1f_IntEn_ADDR;
#define LED7SEG_1f_MASK 0x20
// LED7SEG_1g address and mask defines
#pragma	ioport	LED7SEG_1g_Data_ADDR:	0x0
BYTE			LED7SEG_1g_Data_ADDR;
#pragma	ioport	LED7SEG_1g_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1g_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1g_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1g_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1g_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1g_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1g_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1g_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1g_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1g_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1g_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1g_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1g_IntEn_ADDR:	0x1
BYTE			LED7SEG_1g_IntEn_ADDR;
#define LED7SEG_1g_MASK 0x40
// LED7SEG_1dp address and mask defines
#pragma	ioport	LED7SEG_1dp_Data_ADDR:	0x0
BYTE			LED7SEG_1dp_Data_ADDR;
#pragma	ioport	LED7SEG_1dp_DriveMode_0_ADDR:	0x100
BYTE			LED7SEG_1dp_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1dp_DriveMode_1_ADDR:	0x101
BYTE			LED7SEG_1dp_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1dp_DriveMode_2_ADDR:	0x3
BYTE			LED7SEG_1dp_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1dp_GlobalSelect_ADDR:	0x2
BYTE			LED7SEG_1dp_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1dp_IntCtrl_0_ADDR:	0x102
BYTE			LED7SEG_1dp_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1dp_IntCtrl_1_ADDR:	0x103
BYTE			LED7SEG_1dp_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1dp_IntEn_ADDR:	0x1
BYTE			LED7SEG_1dp_IntEn_ADDR;
#define LED7SEG_1dp_MASK 0x80
// LED7SEG_1Digit0 address and mask defines
#pragma	ioport	LED7SEG_1Digit0_Data_ADDR:	0x4
BYTE			LED7SEG_1Digit0_Data_ADDR;
#pragma	ioport	LED7SEG_1Digit0_DriveMode_0_ADDR:	0x104
BYTE			LED7SEG_1Digit0_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1Digit0_DriveMode_1_ADDR:	0x105
BYTE			LED7SEG_1Digit0_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1Digit0_DriveMode_2_ADDR:	0x7
BYTE			LED7SEG_1Digit0_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1Digit0_GlobalSelect_ADDR:	0x6
BYTE			LED7SEG_1Digit0_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1Digit0_IntCtrl_0_ADDR:	0x106
BYTE			LED7SEG_1Digit0_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1Digit0_IntCtrl_1_ADDR:	0x107
BYTE			LED7SEG_1Digit0_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1Digit0_IntEn_ADDR:	0x5
BYTE			LED7SEG_1Digit0_IntEn_ADDR;
#define LED7SEG_1Digit0_MASK 0x1
// LED7SEG_1Digit0 Shadow defines
//   LED7SEG_1Digit0_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED7SEG_1Digit0_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LED7SEG_1Digit0_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LED7SEG_1Digit0_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LED7SEG_1Digit0_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LED7SEG_1Digit0_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LED7SEG_1Digit1 address and mask defines
#pragma	ioport	LED7SEG_1Digit1_Data_ADDR:	0x4
BYTE			LED7SEG_1Digit1_Data_ADDR;
#pragma	ioport	LED7SEG_1Digit1_DriveMode_0_ADDR:	0x104
BYTE			LED7SEG_1Digit1_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1Digit1_DriveMode_1_ADDR:	0x105
BYTE			LED7SEG_1Digit1_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1Digit1_DriveMode_2_ADDR:	0x7
BYTE			LED7SEG_1Digit1_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1Digit1_GlobalSelect_ADDR:	0x6
BYTE			LED7SEG_1Digit1_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1Digit1_IntCtrl_0_ADDR:	0x106
BYTE			LED7SEG_1Digit1_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1Digit1_IntCtrl_1_ADDR:	0x107
BYTE			LED7SEG_1Digit1_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1Digit1_IntEn_ADDR:	0x5
BYTE			LED7SEG_1Digit1_IntEn_ADDR;
#define LED7SEG_1Digit1_MASK 0x2
// LED7SEG_1Digit1 Shadow defines
//   LED7SEG_1Digit1_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED7SEG_1Digit1_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LED7SEG_1Digit1_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LED7SEG_1Digit1_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LED7SEG_1Digit1_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LED7SEG_1Digit1_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LED7SEG_1Digit2 address and mask defines
#pragma	ioport	LED7SEG_1Digit2_Data_ADDR:	0x4
BYTE			LED7SEG_1Digit2_Data_ADDR;
#pragma	ioport	LED7SEG_1Digit2_DriveMode_0_ADDR:	0x104
BYTE			LED7SEG_1Digit2_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1Digit2_DriveMode_1_ADDR:	0x105
BYTE			LED7SEG_1Digit2_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1Digit2_DriveMode_2_ADDR:	0x7
BYTE			LED7SEG_1Digit2_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1Digit2_GlobalSelect_ADDR:	0x6
BYTE			LED7SEG_1Digit2_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1Digit2_IntCtrl_0_ADDR:	0x106
BYTE			LED7SEG_1Digit2_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1Digit2_IntCtrl_1_ADDR:	0x107
BYTE			LED7SEG_1Digit2_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1Digit2_IntEn_ADDR:	0x5
BYTE			LED7SEG_1Digit2_IntEn_ADDR;
#define LED7SEG_1Digit2_MASK 0x4
// LED7SEG_1Digit2 Shadow defines
//   LED7SEG_1Digit2_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED7SEG_1Digit2_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LED7SEG_1Digit2_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LED7SEG_1Digit2_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LED7SEG_1Digit2_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LED7SEG_1Digit2_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LED7SEG_1Digit3 address and mask defines
#pragma	ioport	LED7SEG_1Digit3_Data_ADDR:	0x4
BYTE			LED7SEG_1Digit3_Data_ADDR;
#pragma	ioport	LED7SEG_1Digit3_DriveMode_0_ADDR:	0x104
BYTE			LED7SEG_1Digit3_DriveMode_0_ADDR;
#pragma	ioport	LED7SEG_1Digit3_DriveMode_1_ADDR:	0x105
BYTE			LED7SEG_1Digit3_DriveMode_1_ADDR;
#pragma	ioport	LED7SEG_1Digit3_DriveMode_2_ADDR:	0x7
BYTE			LED7SEG_1Digit3_DriveMode_2_ADDR;
#pragma	ioport	LED7SEG_1Digit3_GlobalSelect_ADDR:	0x6
BYTE			LED7SEG_1Digit3_GlobalSelect_ADDR;
#pragma	ioport	LED7SEG_1Digit3_IntCtrl_0_ADDR:	0x106
BYTE			LED7SEG_1Digit3_IntCtrl_0_ADDR;
#pragma	ioport	LED7SEG_1Digit3_IntCtrl_1_ADDR:	0x107
BYTE			LED7SEG_1Digit3_IntCtrl_1_ADDR;
#pragma	ioport	LED7SEG_1Digit3_IntEn_ADDR:	0x5
BYTE			LED7SEG_1Digit3_IntEn_ADDR;
#define LED7SEG_1Digit3_MASK 0x8
// LED7SEG_1Digit3 Shadow defines
//   LED7SEG_1Digit3_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED7SEG_1Digit3_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LED7SEG_1Digit3_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LED7SEG_1Digit3_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LED7SEG_1Digit3_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LED7SEG_1Digit3_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LCD_1E address and mask defines
#pragma	ioport	LCD_1E_Data_ADDR:	0x4
BYTE			LCD_1E_Data_ADDR;
#pragma	ioport	LCD_1E_DriveMode_0_ADDR:	0x104
BYTE			LCD_1E_DriveMode_0_ADDR;
#pragma	ioport	LCD_1E_DriveMode_1_ADDR:	0x105
BYTE			LCD_1E_DriveMode_1_ADDR;
#pragma	ioport	LCD_1E_DriveMode_2_ADDR:	0x7
BYTE			LCD_1E_DriveMode_2_ADDR;
#pragma	ioport	LCD_1E_GlobalSelect_ADDR:	0x6
BYTE			LCD_1E_GlobalSelect_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_0_ADDR:	0x106
BYTE			LCD_1E_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_1_ADDR:	0x107
BYTE			LCD_1E_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1E_IntEn_ADDR:	0x5
BYTE			LCD_1E_IntEn_ADDR;
#define LCD_1E_MASK 0x10
// LCD_1E Shadow defines
//   LCD_1E_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LCD_1E_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LCD_1E_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LCD_1E_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LCD_1E_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LCD_1E_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LCD_1RS address and mask defines
#pragma	ioport	LCD_1RS_Data_ADDR:	0x4
BYTE			LCD_1RS_Data_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_0_ADDR:	0x104
BYTE			LCD_1RS_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_1_ADDR:	0x105
BYTE			LCD_1RS_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_2_ADDR:	0x7
BYTE			LCD_1RS_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RS_GlobalSelect_ADDR:	0x6
BYTE			LCD_1RS_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_0_ADDR:	0x106
BYTE			LCD_1RS_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_1_ADDR:	0x107
BYTE			LCD_1RS_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RS_IntEn_ADDR:	0x5
BYTE			LCD_1RS_IntEn_ADDR;
#define LCD_1RS_MASK 0x20
// LCD_1RS Shadow defines
//   LCD_1RS_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LCD_1RS_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LCD_1RS_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LCD_1RS_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LCD_1RS_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LCD_1RS_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LCD_1RW address and mask defines
#pragma	ioport	LCD_1RW_Data_ADDR:	0x4
BYTE			LCD_1RW_Data_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_0_ADDR:	0x104
BYTE			LCD_1RW_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_1_ADDR:	0x105
BYTE			LCD_1RW_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_2_ADDR:	0x7
BYTE			LCD_1RW_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RW_GlobalSelect_ADDR:	0x6
BYTE			LCD_1RW_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_0_ADDR:	0x106
BYTE			LCD_1RW_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_1_ADDR:	0x107
BYTE			LCD_1RW_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RW_IntEn_ADDR:	0x5
BYTE			LCD_1RW_IntEn_ADDR;
#define LCD_1RW_MASK 0x40
// LCD_1RW Shadow defines
//   LCD_1RW_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LCD_1RW_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
//   LCD_1RW_DriveMode_0Shadow define
extern BYTE Port_1_DriveMode_0_SHADE;
#define LCD_1RW_DriveMode_0Shadow (*(unsigned char*)&Port_1_DriveMode_0_SHADE)
//   LCD_1RW_DriveMode_1Shadow define
extern BYTE Port_1_DriveMode_1_SHADE;
#define LCD_1RW_DriveMode_1Shadow (*(unsigned char*)&Port_1_DriveMode_1_SHADE)
// LED_BLPin address and mask defines
#pragma	ioport	LED_BLPin_Data_ADDR:	0x8
BYTE			LED_BLPin_Data_ADDR;
#pragma	ioport	LED_BLPin_DriveMode_0_ADDR:	0x108
BYTE			LED_BLPin_DriveMode_0_ADDR;
#pragma	ioport	LED_BLPin_DriveMode_1_ADDR:	0x109
BYTE			LED_BLPin_DriveMode_1_ADDR;
#pragma	ioport	LED_BLPin_DriveMode_2_ADDR:	0xb
BYTE			LED_BLPin_DriveMode_2_ADDR;
#pragma	ioport	LED_BLPin_GlobalSelect_ADDR:	0xa
BYTE			LED_BLPin_GlobalSelect_ADDR;
#pragma	ioport	LED_BLPin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_BLPin_IntCtrl_0_ADDR;
#pragma	ioport	LED_BLPin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_BLPin_IntCtrl_1_ADDR;
#pragma	ioport	LED_BLPin_IntEn_ADDR:	0x9
BYTE			LED_BLPin_IntEn_ADDR;
#define LED_BLPin_MASK 0x10
// LED_BLPin Shadow defines
//   LED_BLPin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_BLPin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
